### PR TITLE
Solo support ruiyu

### PR DESCRIPTION
**Pull request by RuiyuZ**

### CODE REVIEW

**Review by mkamalza — CHANGES_REQUESTED** [review]
Nice work. Thanks for taking on this huge task. Here are some issues I came across so far. Some may be bugs and some may be platform specific. Let me know if any of them are not reproducible on your side:

- What is the user experience when installing? Does the new unity-vision dependency get installed when the user runs "pip install unity-cv-datasetvisualizer" or does it need explicit installation?

- We need to organize the sample dataset folders. We can put them all in a "Sample Datasets" folder and give them good names.

- Opening a UCVD dataset results in a blank screen

- When a new dataset is opened, we need to go to index 0. Currently it stays on the previous index, which might not exist in the new dataset.

- Semantic segmentation images in the dataset solo_human_and_box do not include the humanoid model. Is this expected?

- The dataset named "solo" and "solo_1" and "solo_2" result in a blank screen when opened.

- With "solo_human_and_box", why is there a separation between keypoint and keypoint_0? I think there should just be a switch for showing keypoints or not.

- Trying to display 3D bounding boxes on "Sample Dataset - Shapes" results in the error below (seems to happen on all legacy datasets):

AttributeError: 'dict' object has no attribute 'matrix'
Traceback:

File "/Users/mohsenkamalzadeh/opt/miniconda3/envs/dv_solo_env/lib/python3.7/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/Preview.py", line 136, in <module>
    preview_app({"data": None})
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/Preview.py", line 119, in preview_app
    create_select_dataset_page(args["data"])
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/Preview.py", line 83, in create_select_dataset_page
    legacy_preview_dataset(data_root, folder_name)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/LegacyPreview.py", line 184, in preview_dataset
    grid_view(num_rows, ds, labelers)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/LegacyPreview.py", line 330, in grid_view
    image = ds.get_image_with_labelers(i, labelers, max_size=get_resolution_from_num_cols(num_cols))
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/LegacyDataset.py", line 151, in get_image_with_labelers
    image = v.draw_image_with_box_3d(image, sensor, annotations, None)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/visualization/visualizers.py", line 245, in draw_image_with_box_3d
    i = sensor.matrix


- Trying to display 2D bounding boxes on "legacy" and "Sample Dataset - Shapes" results in the error below (seems to happen on all legacy datasets):

TypeError: draw_image_with_boxes() takes 2 positional arguments but 4 were given
Traceback:

File "/Users/mohsenkamalzadeh/opt/miniconda3/envs/dv_solo_env/lib/python3.7/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/Preview.py", line 136, in <module>
    preview_app({"data": None})
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/Preview.py", line 119, in preview_app
    create_select_dataset_page(args["data"])
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/Preview.py", line 83, in create_select_dataset_page
    legacy_preview_dataset(data_root, folder_name)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/LegacyPreview.py", line 184, in preview_dataset
    grid_view(num_rows, ds, labelers)
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/LegacyPreview.py", line 330, in grid_view
    image = ds.get_image_with_labelers(i, labelers, max_size=get_resolution_from_num_cols(num_cols))
File "/Users/mohsenkamalzadeh/Documents/GitHub/com.unity.cv.datasetvisualizer/Unity_CV_DatasetVisualizer/datasetvisualizer/LegacyDataset.py", line 134, in get_image_with_labelers
    label_mappings,

**Comment by StevenBorkman** [comment]
We should probably remove the sample databases from the repo

**Review by StevenBorkman — APPROVED** [review]
I left a comment about removing the datasets in the baseline, other than that it looks good

**Comment by RuiyuZ** [comment]
> I left a comment about removing the datasets in the baseline, other than that it looks good

Thanks Steve! I just removed them

**Pull request merged**
